config/routes.rb
Rails.application.routes.draw do
	root'posts#index', as: "home"
	get'about' => 'pages#about', as: "about"

	resources :posts do
		resources :comments
	end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
has_attached_file :image, styles: { medium: "500x500>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	has_many :comments
	validates :title, presence: true,
	                    Length: {minimum: 5}
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with name: "Geoffrey", password:"1234", only: [:destroy]
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		redirect_to post_path(@post)
end

def destroy
    @post = Post.find(params[:post_id])
	@comment = @post.comments.find(params[:id])
	@comment.destroy
	redirect_to post_path(@post)
	
end 


private def comment_params
    params.require(:comment).permit(:username, :body)
    end
end    

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@title = 'About Us';
		@content = 'this is our about page ';
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	http_basic_authenticate_with name: "Geoffrey", password:"1234", except: [:index, :show]

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new

	end

	def create
	    @post = Post.new(permit_post)

	    if@post.save
	    	flash[:success] = "success!"
	       redirect_to post_path(@post)
	    else
	    	flash[:error] = @post.errors.full_messages
	    	rendirect_ro new_post_path
	    end
	end

	def edit
		@post = Post.find(params[:id])

	end

	def update
		@post = Post.find(params[:id])

		 if(@post.update(post_params))
	       redirect_to @post
	    else
	    	render 'edit'
	    end

	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		
		redirect_to posts_path
	end

	private def permit_post
	  params.require(:post).permit(:title, :body, :image)
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>comments</h3>
<% @post.comments.each do |comment| %>
    <div class="well">
    <p><strong><%= comment.username %></strong>: <%= comment.body %>
    <%= link_to '[x]', [comment.post, comment],
                method: :delete,
                data:{confirm: 'Are you sure?'},
                 :class =>'btn btn-default' %>
    </p>
    </div>
 <% end %>

app/views/comments/_form.html.erb
<h3>Add comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
   
 <p>
  <%= f.label :username %><br>
  <%=f.text_field(:username, {:class => "form-control"}) %>,
  </p>

 <p>
   <%= f.label :body %><br>
   <%= f.text_area(:body, {:clas => "form-control"}) %>
 </p>

 <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
 </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odhisblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application','data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">odhisblog</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
         <ul class="nav navbar-nav">
            <li><%= link_to "Home", home_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Create post", new_post_path %></li>
          </ul>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

  <div class="container background-pic" >
      <%= yield %>
   </div> 
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post) do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
          <div class="alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
 <p>
  <%= f.label :title %><br>
  <%=f.text_field(:title, {:class => "form-control"}) %>
</p>

 <p>
   <%= f.label :body %><br>
   <%= f.text_area(:body, {:clas => "form-control"}) %>


 <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
 </p>
<% end %>

app/views/posts/index.html.erb
<h1 class="home">THE WORLD AND ITS(D)MERITS</h1>
<% @posts.each do |post| %>
    <div class="white"
	   <h3><%= post.title %></h3>
	   <p><%= post.body %></p>
	   <%= image_tag post.image.url(:medium) %>

	   <%= link_to "read more", post_path(post), :class => 'btn btn-default' %>
	</div>
<% end %>s

app/views/posts/new.html.erb
<h1>Add Post</h1>
<hr>

<%= form_for :post, url: posts_path,  html: { multipart: true }  do |f| %>
<br>


    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
          <div class="alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
  <p>
   <%= f.label :title %><br>
   <%=f.text_field(:title, {:class => "form-control"}) %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:clas => "form-control"}) %>
    <br>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<%= image_tag(@post.image.url(:medium)) %>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class =>'btn btn-default' %>
<%= link_to "Delete", post_path(@post),
                method: :delete,
                data: {confirm: 'Are you sure?'},
                 :class =>'btn btn-danger' %>
<hr>


<%= render "comments/comments" %>
<%= render "comments/form" %>